# Generated by Django 4.0.4 on 2022-06-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text_about',
        ),
    ]
