# Generated by Django 4.0.5 on 2022-06-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
